spring:
  config:
    activate:
      on-profile: "prd"

build:
  version: "1.0"

cards:
  message: "Welcome to SpringBank cards related PRD APIs "
  contactDetails:
    name: "Ganesh Shet - PRD Lead"
    email: "ganesh@springbank.com"
  onCallSupport:
    - (666) 265-3764
    - (666) 734-8373