spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to SpringBank cards related QA APIs "
  contactDetails:
    name: "Ganesh Shet - QA Lead"
    email: "ganesh@springbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371

